# RuboCop configuration for Rails Blog Application
# This file contains the configuration for RuboCop, a Ruby static code analyzer

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.0
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/**/*'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - 'config/initializers/devise.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

# Layout
Layout/LineLength:
  Max: 100
  Exclude:
    - 'config/routes.rb'
    - 'config/initializers/*'

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

# Style
Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/Lambda:
  EnforcedStyle: literal

# Metrics
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'db/seeds.rb'
    - 'lib/tasks/**/*.rake'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/*'

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 20

# Rails specific
Rails/FilePath:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/InverseOf:
  Enabled: true

Rails/Presence:
  Enabled: true

Rails/Present:
  Enabled: true

Rails/Blank:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

# RSpec specific
RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 5

RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/**/*'
    - 'spec/features/**/*'
    - 'spec/system/**/*'

# Security
Security/YAMLLoad:
  Enabled: true

Security/Eval:
  Enabled: true

# Naming
Naming/VariableNumber:
  Enabled: false

# Bundler
Bundler/OrderedGems:
  Enabled: false
