# Dockerfile for initial Rails app setup
FROM ruby:3.1.0-alpine

# Install base dependencies
RUN apk add --no-cache build-base nodejs yarn git

# Install Rails gem
RUN gem install rails -v 7.0.4

# Set working directory
WORKDIR /app

# We don't copy any files in, this image is just for running rails new
CMD ["rails", "new"]
